USE AppleStore
GO

INSERT INTO Categories VALUES(20, 'AirPods')
ALTER DATABASE AppleStore SET ALLOW_SNAPSHOT_ISOLATION ON

WAITFOR DELAY '00:00:05'
BEGIN TRAN
UPDATE Categories SET catName = 'MacBook' WHERE catID = 20
WAITFOR DELAY '00:00:05'
COMMIT TRAN

-- ALTER DATABASE AppleStore SET ALLOW_SNAPSHOT_ISOLATION OFF
-- UPDATE Categories SET catName = 'Watch' WHERE catID = 20
-- SELECT * FROM Categories

