-- DROP DATABASE STATEMENTS
USE master 
GO
ALTER DATABASE AppleStore 
SET single_user WITH ROLLBACK IMMEDIATE
DROP DATABASE AppleStore

-- CREATE DATABASE STATEMENTS
CREATE DATABASE AppleStore

GO
USE AppleStore
GO

-- DROP STATEMENTS
DROP TABLE Payment;
DROP TABLE Deliveries;
DROP TABLE Orders;
DROP TABLE Work_In;
DROP TABLE Stores;
DROP TABLE Employee;
DROP TABLE Products;
DROP TABLE Available_Categories;
DROP TABLE Available_Model;
DROP TABLE Model;
DROP TABLE Colour;
DROP TABLE Customers;
DROP TABLE Categories;

-- CREATE TABLE STATEMENTS
CREATE TABLE Categories (
	catID INT PRIMARY KEY IDENTITY, -- auto increments primary key = personl/unique id
	catName VARCHAR(30) NOT NULL
);

CREATE TABLE Model (
	modID INT PRIMARY KEY IDENTITY,
	catID INT FOREIGN KEY REFERENCES Categories(catID) NOT NULL, -- foreign key = an id taken from another table
	modName VARCHAR(30) NOT NULL
);

CREATE TABLE Colour (
	-- m(colours):n(products)
	colID INT PRIMARY KEY IDENTITY,
	colName VARCHAR(30) NOT NULL
);

CREATE TABLE Available_Model (
	colID INT FOREIGN KEY REFERENCES Colour(colID) NOT NULL,
	modID INT FOREIGN KEY REFERENCES Model(modID) NOT NULL,
	CONSTRAINT PK_Available_Model PRIMARY KEY (colID, modID)
);

CREATE TABLE Available_Categories (
	colID INT FOREIGN KEY REFERENCES Colour(colID) NOT NULL,
	catID INT FOREIGN KEY REFERENCES Categories(catID) NOT NULL,
	CONSTRAINT PK_Available_Categories PRIMARY KEY (colID, catID)
);

CREATE TABLE Stores (
	-- 1(store):n(employees)
	stoID INT PRIMARY KEY IDENTITY,
	stoLoc VARCHAR(200) NOT NULL
);

CREATE TABLE Products (
	-- m(products):n(colours)
	proID INT PRIMARY KEY IDENTITY,
	modID INT FOREIGN KEY REFERENCES Model(modID) NOT NULL,
	colID INT FOREIGN KEY REFERENCES Colour(colID) NOT NULL,
	proName VARCHAR(100) NOT NULL,
	proDescription VARCHAR(500) NOT NULL,
	proRate INT
);

CREATE TABLE Employee (
	empID INT PRIMARY KEY IDENTITY,
	catID INT FOREIGN KEY REFERENCES Categories(catID) NOT NULL,
	empName VARCHAR(100) NOT NULL,
	empSalary INT,
	empWork INT,
	empJob VARCHAR(100) NOT NULL, 
	empExperience INT
);

CREATE TABLE Work_In (
	stoID INT FOREIGN KEY REFERENCES Stores(stoID) NOT NULL,
	empID INT FOREIGN KEY REFERENCES Employee(empID) NOT NULL,
	CONSTRAINT PK_Work_In PRIMARY KEY (stoID, empID)
);

CREATE TABLE Customers (
	-- 1(customer):n(orders)
	cusID INT PRIMARY KEY IDENTITY,
	cusName VARCHAR(100) NOT NULL,
	cusPhoneNr INT,
	cusAdrres VARCHAR(200) NOT NULL
);

CREATE TABLE Orders (
	ordID INT PRIMARY KEY IDENTITY,
	cusID INT FOREIGN KEY REFERENCES Customers(cusID) NOT NULL,
	proID INT FOREIGN KEY REFERENCES Products(proID) NOT NULL,
	ordDate DATE
);

CREATE TABLE Payment (
	ordID INT FOREIGN KEY REFERENCES Orders(ordID) NOT NULL,
	payDate DATE,
	payType VARCHAR(50),
	CONSTRAINT PK_Payment PRIMARY KEY (ordID)
);

CREATE TABLE Deliveries (
	delID INT PRIMARY KEY IDENTITY,
	ordID INT NOT NULL,
	CONSTRAINT FK_Deliveries FOREIGN KEY (ordID) REFERENCES Orders(ordID),
	delDate DATE
);